### ISSUE TITLE
今後の開発予定

### ISSUE THREAD

**Issue by irohanihohe10** [rohme/BoxUnlocker#1]
BoxUnlockerの今後の開発予定などはあるのでしょうか？

**Comment by rohme** [comment]
これ初めて作ったプログラムなので、作り直しをしようかと思っているくらいで、
特に開発予定とかは無いのですが、面白そうな提案があれば実装するかもしれません。

**Comment by irohanihohe10** [comment]
ナンバー系？は網羅されているようなので完成している感がありますよね。
新しい提案は思いつかなかったのですが、作り直し版がリリースされるのを楽しみにしています。

Bokkaなどにも最近気づいたのですがこういうものを開発できてしまうってすごいですねｗ

**Comment by rohme** [comment]
FFACEとか使用すれば、結構簡単に作ることができますよ。
VisualStudioも唯で手に入りますし、良い時代になったものです。

**Comment by rohme** [comment]
作り直したぞー

**Comment by irohanihohe10** [comment]
おおおー！ありがとうございます！！！
