### ISSUE TITLE
v0.9.0でMUMのキーナンバー99の失敗が認識されない

### ISSUE THREAD

**Issue by irohanihohe10** [rohme/BoxUnlocker#2]
いつも楽しくツールを使わせていただいています。ありがとうございます。
BoxUnlockerでMUMのキーナンバー99をやっていると失敗がうまく認識されていないようです。
順番に数字を絞っていって、失敗して、次のゲームに移っても、そのまま前回の数値を入力してしまいます。
回数：6/5のように5/5をオーバーした状態で処理が進んでいきます。
BoxUnlockerのログ欄には「失敗した」というログがでません。
Treasure Casketの方は問題なく使えています。

**Comment by rohme** [comment]
不具合報告ありがとうございます。
Ver1.0.0にて対応しました。

**Comment by irohanihohe10** [comment]
ありがとうございました！
本当にいつもありがとうございます。
さっそく使わせていただきます。
